"""add_recurring_category_fields

Revision ID: ba82be13234e
Revises: eac460f2c723
Create Date: 2026-01-12 02:25:18.113354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba82be13234e'
down_revision: Union[str, None] = 'eac460f2c723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Enum型を作成
    op.execute("CREATE TYPE recurringfrequency AS ENUM ('MONTHLY', 'YEARLY')")

    # まずNULL可能なカラムとして追加
    op.add_column('categories', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    # 既存レコードにデフォルト値を設定
    op.execute("UPDATE categories SET is_recurring = FALSE WHERE is_recurring IS NULL")
    # NOT NULL制約を追加
    op.alter_column('categories', 'is_recurring', nullable=False)

    op.add_column('categories', sa.Column('frequency', sa.Enum('MONTHLY', 'YEARLY', name='recurringfrequency'), nullable=True))
    op.add_column('categories', sa.Column('default_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'default_amount')
    op.drop_column('categories', 'frequency')
    op.drop_column('categories', 'is_recurring')
    # Enum型を削除
    op.execute("DROP TYPE recurringfrequency")
    # ### end Alembic commands ###
